### ISSUE TITLE
Populate data subtype in MySQL connector

### ISSUE THREAD

**Issue by k15z** [data-dev/MetaData#11]
A common issue that occurs in downstream applications is when integer-valued columns (i.e. id/key columns) are treated as floats. Whenever possible, the MySQL connector should populate the subtype field with the appropriate value.

Furthermore, it may also make sense to directly add a `load_dataset` method to this library which produces a DataFrame with the appropriate types based on `data_type` and `data_subtype`.

**Comment by csala** [comment]
Fixed via #12
