### ISSUE TITLE
Modifying the schema to support non-unique table names

### ISSUE THREAD

**Issue by k15z** [data-dev/MetaData#13]
Currently, the `Table` object contains a `name` field which we assume can be used to uniquely identify a table. However, in some scenarios, the data may originate from multiple systems (i.e. a MySQL instance + a hadoop instance) and there could be multiple tables with the same name but different values.

## Design
The current proposal is to introduce a new `id` field in the `Table` object which will uniquely identify each table in a metadata object.

```
{
    "id": "f0b5fbc3-f50d-4748-b6a2-acfd3ec350f5",
    "name": "users",
    "fields": [ ... ]
}
```

Then, when referring to a field in the foreign key object, it would use the `id` value to reference the table.

```
{
    "table": "f0b5fbc3-f50d-4748-b6a2-acfd3ec350f5",
    "field": "user_id",
    "ref_table": "61a15891-b4ea-4ee3-b500-ea7b89ecf096"
    "ref_field: "sender_id"
}
```

Similarly, in the constraint object, the field object would reference the table id (as opposed to the table name).

## Alternates
**Alternative 1.** We could modify the foreign key and constraint schemas to accept an optional `system`/`application` field which can be used to disambiguate table names if they are not unique.

**Alternative 2.** We could require that users namespace their table names (i.e. the table names should be `mysql.users` and `hadoop.users`) so they are always unique. This would not require any modifications to the schema.

**Comment by csala** [comment]
Closed via #17
